name: Validate and Auto Publish

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/respec-w3c-auto-publish@v1 # use the action
        with:
          ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          ECHIDNA_MANIFEST_URL: "https://w3c.github.io/webrtc-stats/W3CTRMANIFEST"
          # Please use the URL that's appropriate for your working group!
          WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html"
          CC: "dom@w3.org"
          INPUT_FILE: webrtc-stats.html
          CHECK_LINKS: false
